### ISSUE TITLE
package in main npm repository

### ISSUE THREAD

**Issue by vgrichina** [MaxGraey/bignum.wasm#32]
It'll be nice to have bignum.wasm published in main npm repository. It's very error-prone (and slow) to depend on packages on GitHub.

We might need to have to create own fork and publish ourselves if there is no official package.

**Comment by MaxGraey** [comment]
Sure. I guess it's time to ship it on npm.

**Comment by vgrichina** [comment]
@MaxGraey any update on this?

**Comment by vgrichina** [comment]
@MaxGraey friendly ping on this. Should we give up and publish our own npm package?

**Comment by MaxGraey** [comment]
Done! https://www.npmjs.com/package/as-bignum

**Comment by MaxGraey** [comment]
Make sure you change to `import { u128 } from "as-bignum"`. Previous `import { u128 } from "bignum"` not work anymore
