### ISSUE TITLE
Need to release a new version. The import path is invalid now

### ISSUE THREAD

**Issue by yjhmelody** [MaxGraey/bignum.wasm#79]
```sh
$ asc ./index.ts --noEmit --measure
ERROR TS6054: File '~lib/as-bignum.ts' not found.
   :
 3 │ export { i128, u128, u256 } from "as-bignum";
   │                                  ~~~~~~~~~~~
   └─ in assembly/index.ts(3,34)
```

**Comment by MaxGraey** [comment]
You should use `from "as-bignum/assembly"` in your code. See example:
https://github.com/MaxGraey/as-bignum#usage-via-assemblyscript

**Comment by yjhmelody** [comment]
Ok, It will be better to support `from "as-bignum"`. Maybe just change `"main": "./assembly"

**Comment by MaxGraey** [comment]
`"ascMain"` hint was dropped in AssemblyScript after 0.20.x. So it's not a library problem
